version: "2"
services:

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PlasmaDB
    #    volumes:
    #      - '/opt/datasql:/var/lib/mysql'
    network_mode: host

  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    container_name: mongo
    network_mode: host

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15673:15673
      - 5673:5673
    network_mode: host

  neo4j:
    image: neo4j:3.5
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    network_mode: host
    restart: always
    volumes:
      - ./neo4j/import:/import
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/Neo4j
    expose:
      - 7474

  apigateway:
    image: zuul-service
    build: zuul-gatewayservice/
    restart: always
    network_mode: host
    depends_on:
    - eurekaserver
    ports:
    - 8092:8092
    expose:
    - 8092

  eurekaserver:
    image: eureka-service:latest
    build: eureka-server/
    restart: always
    network_mode: host
    ports:
    - 9091:9091
    expose:
    - 9091

  configserver:
      image: config-service:latest
      build: config-server/
      restart: always
      network_mode: host
      ports:
      - 8888:8888
      expose:
      - 8888
 
  documentcrawler:
    image: document-crawler-service:latest
    build: document-crawler-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - rabbitmq
    ports:
      - 8193:8193
    expose:
      - 8193

  searchservice:
    image: search-service:latest
    build: search-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - rabbitmq
      - mongo
    ports:
      - 8090:8090
    expose:
      - 8090

  nlpservice:
    image: nlp-service:latest
    build: nlp-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - mongo
    ports:
      - 8098:8098
    expose:
      - 8098

  evaluatorservice:
    image: evaluator-service:latest
    build: evaluator-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
    ports:
      - 8082:8082
    expose:
      - 8082

  userloginservice:
    image: user-login-service:latest
    build: user-login-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - mysql
    ports:
      - 8132:8132
    expose:
      - 8132

  userregisterservice:
    image: user-register-service:latest
    build: user-register-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - mongo
    ports:
      - 8089:8089
    expose:
      - 8089
  
  knowledgeindexerservice:
    image: knowledge-indexer-service:latest
    build: knowledge-indexer-service/
    restart: always
    network_mode: host
    depends_on:
      - neo4j
      - eurekaserver
      - rabbitmq
      - configserver
    ports:
      - 8085:8085
    expose:
      - 8085

  knowledgequeryservice:
    image: knowledge-query-service:latest
    build: knowledge-query-service/
    restart: always
    network_mode: host
    depends_on:
      - neo4j
      - eurekaserver
      - rabbitmq
      - configserver
    ports:
      - 8086:8086
    expose:
      - 8086

  plasmafrontend:
    build: plasma-frontend/
    image: plasma-frontend:latest
    container_name: plasma-frontend
    network_mode: "host"
    hostname: localhost
    ports:
      - 4200:4200
    restart: always

  taggingservice:
    image: tagging-service:latest
    build: tagging-service/
    restart: always
    network_mode: host
    depends_on:
     - eurekaserver
    ports:
     - 8087:8087
    expose:
     - 8087